# Generated by Django 4.1.7 on 2023-03-15 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0002_alter_user_managers_alter_user_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='user',
            name='status',
            field=models.IntegerField(default=1),
        ),
    ]
